[package]
name = "nbm-tools"
version = "0.1.1"
authors = ["Ryan <rnleach@users.noreply.github.com>"]
description = "A library for parsing and analyzing NBM 1D text files."
publish = false

edition = "2018"

[profile.release]
lto = "fat"

[dependencies]
chrono = "^0.4"
optional = "^0.5.0"

